# This is a config for E2B sandbox template.
# You can use 'template_id' (w9nfeev5mm8a64f8tqw2) or 'template_name (code-interpreter-stateful-lab) from this config to spawn a sandbox:

# Python SDK
# from e2b import Sandbox
# sandbox = Sandbox(template='code-interpreter-stateful-lab')

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create({ template: 'code-interpreter-stateful-lab' })

memory_mb = 1_024
start_cmd = "/root/.jupyter/start-up.sh"
dockerfile = "e2b.Dockerfile"
template_name = "code-interpreter-stateful-lab"
template_id = "w9nfeev5mm8a64f8tqw2"
