# This is a config for E2B sandbox template.
# You can use 'template_id' (6rn8gnglohgpuk1wsack) or 'template_name (ci-no-ws) from this config to spawn a sandbox:

# Python SDK
# from e2b import Sandbox
# sandbox = Sandbox(template='ci-no-ws')

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create({ template: 'ci-no-ws' })

memory_mb = 1_024
start_cmd = "/root/.jupyter/start-up.sh"
dockerfile = "e2b.Dockerfile"
template_name = "ci-no-ws"
template_id = "6rn8gnglohgpuk1wsack"
